import Home from "./Home";
import NotFound from "./NotFound";
import MenuItemDetails from "./MenuItemDetails";
import ShoppingCart from "./shoppingCart";
import Login from "./Login";
import Register from "./Register";
import AccessDenied from "./AccessDenied";
import AuthenticationTest from "./AuthenticationTest";
import AuthenticationTestAdmin from "./AuthenticationTestAdmin";
import Payment from "./Payment";
import PaymentQuick from "./PaymentQiuck";
export {Home, NotFound, MenuItemDetails, ShoppingCart, Login, Register, AccessDenied, AuthenticationTest, AuthenticationTestAdmin, Payment, PaymentQuick};